### ISSUE TITLE
Hide Status bar for DetailViewController 

### ISSUE THREAD

**Issue by JDSX** [PaoloCuscela/Cards#27]
When transitioning to fullscreen mode I have hidden the status bar, however the scroll view still appears 20px from the top. 

I have set the following properties

        scrollView.frame.origin.y = 0
        
        if isFullscreen {
            scrollView.frame = view.frame

        }

However there's still white space like so

<img width="379" alt="screen shot 2017-11-24 at 00 40 40" src="https://user-images.githubusercontent.com/5117290/33191368-88eab2a6-d0b0-11e7-81bd-0e216786755d.png">

**Comment by PaoloCuscela** [comment]
Right now I can't figure out why this happens. Probably because of safe area insets, but it looks really strange cause snapshotView and blurView take whole screen ignoring these insets.

If you print view and scrollView's frame just after setting scrollView.frame = view.frame it returns:
View = ( 0, **0**, width, height )
ScrollView ( 0, **45**, width, height )

**Comment by cyrilzakka** [comment]
In DetailViewController for iOS 11, set `scrollView.contentInsetAdjustmentBehavior = .never`.

**Comment by PaoloCuscela** [comment]
Thanks, updated.
