### ISSUE TITLE
Remove 'view' button

### ISSUE THREAD

**Issue by J7mbo** [PaoloCuscela/Cards#34]
Can we have the view button removable or interchangeable. Maybe make it a public property or just provide a method to get it and set it to nil?

**Comment by PaoloCuscela** [comment]
Sure, i can maybe hide the button when its text is set to nil or "".

**Comment by J7mbo** [comment]
That would be great, thanks! Want a PR or do you want to do this?

**Comment by PaoloCuscela** [comment]
Sure, a PR would be great 👍

**Comment by mymikemiller** [comment]
Another option is to use a CardArticle instead of a CardHighlight if you don't mind also removing the icon, not taking up the full screen when showing the detail view, and not having an "x" in the upper-right to close the detail view.

I propose changing CardArticle to behave more like the article cards do in the App Store: take up the full screen when opened (no margins on left and right), and have an "x" button in the top right that stays there as long as the details are showing (the CardHighlight details page doesn't show the "x" until the card is scrolled down a bit; in the App Store, the "x" is always there)

**Comment by danilobias** [comment]
Hi,
I'd like to use CardHighlight without the "view" button, but I do not think that's possible even on the last release.

Is there any way to hide this button?

**Comment by PaoloCuscela** [comment]
While I’m adding this feature you could try to comment this line in cardHighlight.swift
‘’’swift
backgroundIV.addSubview(actionBtn)
‘’’

**Comment by PaoloCuscela** [comment]
I' ve pushed the feature you asked for :D.
It will be in the next release. If you  want to test it out:
Change in CardHighlight.swift
```swift
/**
     Text for the card's button.
     Set to [nil] or "" to hide the button.
     */
    @IBInspectable public var buttonText: String? = "view" {
        didSet{
            self.actionBtn.isHidden = (buttonText == nil || buttonText!.isEmpty)
            self.setNeedsDisplay()
        }
    }
```

and in draw(rect:) before 'layout()'
```swift
if self.buttonText != nil {
  let btnTitle = NSAttributedString(string: buttonText!.uppercased(), attributes: [ NSAttributedString.Key.font : UIFont.systemFont(ofSize: 16, weight: .black), NSAttributedString.Key.foregroundColor : self.tintColor])
  actionBtn.setAttributedTitle(btnTitle, for: .normal)
  btnWidth = CGFloat((buttonText!.count + 2) * 10)
}
```
